### ISSUE TITLE
Only Programmer 1 can enable issues/ github pages

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/git-workflow-workshop-for-two#22]
In step 2 it asks for Programmer 2 to enable GitHub pages. Programmer 2 cannot do this. It should ask for Programmer 1 to enable GitHub pages and Issues.

**Comment by jsms90** [comment]
Thanks for raising this and helping to improve our curriculum @astroash!!

@PiotrBerebecki is the original author. Piotr, how would you like to proceed?

**Comment by PiotrBerebecki** [comment]
Awesome 👍  I've just opened a PR #35 to fix this issue

**Comment by jsms90** [comment]
@astroash Are you happy with the changes? If so, feel free to close the issue :+1:

**Comment by astroash** [comment]
All looks great to me, thanks @PiotrBerebecki
