### ISSUE TITLE
remove forking from workflow

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/git-workflow-workshop-for-two#29]
It's really cool for students to learn how to add other collaborators to their own github projects (on their personal profile) :+1: This would be really useful for them in the future and/or if they want to contribute to other open source projects.

But the forking workflow is _not_ what they will be using at FAC. All of the projects that they make whilst on FAC should be created under the `foundersandcoders` or `FAC-X` organisations, precisely because their fellow students are then _automatically_ contributors.

It would be more useful to teach them the workflow that they will be using during their time at FAC i.e. no forking. Perhaps there could be a "bonus level" at the end, for explaining how to contribute to external (open source) projects?

**Comment by PiotrBerebecki** [comment]
Great tip 👍  I've just added a note at the end to explain this.

**Comment by jsms90** [comment]
Sorry @PiotrBerebecki I kind of mean the opposite. This workshop is the first time that students are being taught about git and github.

I think the forking workflow might be a useful footnote. But we should use this workshop to introduce students to the workflow that we expect them to use for the projects.

**Comment by jsms90** [comment]
How about we introduce them to the same flow they will be using in projects later?

Step 1 - create a new repo under your cohort's github organisation. Initialise with readme

Step 2 - `git clone`

Step 3 - raise an issue

Step 4 - create and move to a new branch called `add-heading`

Step 5 - create a new HTML file called `index.html`
```
example goes here (directly in the instructions)
```

Step 6 - `git add`

Step 7 - `git commit` (with multi-line comment - very important when they're contributing to FAC)

Step 7 - `git push`

Then start from the current "step 4" in your workshop?

**Comment by PiotrBerebecki** [comment]
That would be perfect and I'm OK for FAC11 to add this change.

**Comment by jsms90** [comment]
Also, we have 8 pull requests (many of them merged) from students https://github.com/foundersandcoders/git-workflow-workshop-for-two/pulls?q=is%3Apr+is%3Aclosed because they've submitted PRs to this repo instead of the forked version that's sitting in their own profiles, as you no doubt intended
