### ISSUE TITLE
Step 13 seems to refer to P1 rather than P2

### ISSUE THREAD

**Issue by morkeltry** [foundersandcoders/git-workflow-workshop-for-two#33]
The whole of this step should be done by Programmer 2!

>
>*   Programmer 2 tries to merge master branch into update-class-heading branch.
>
>*  There should be a :boom: merge conflict :boom: since the line with theh1 heading is different. >Merge conflict should be highlighted with HEAD and master markers as follows:
>
>
 >* Programmer 1 removes HEAD and master markers and leaves only one line with h1 heading so that both issues are addressed.
>
 >*  Programmer 1 adds the index.html file to staging area and commits the changes occurred during the merge conflict.

**Comment by PiotrBerebecki** [comment]
Thanks @morkeltry for opening an issue 👍  This has now been fixed.
