### ISSUE TITLE
clarify that we use the github flow i.e. branch = feature

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/git-workflow-workshop-for-two#38]
Trying to solve https://github.com/foundersandcoders/master-reference/issues/398

Can we do this in your workshop somehow?

See [FAC11's stop go continue](https://github.com/foundersandcoders/london-curriculum/blob/master/stop-go-continue/fac-11/cohort-week-1.md#stop)
> Always create a branch when working on a feature, don't work on master.
> Making it clearer that branches are made for specific features.

See [the paragraphs](https://github.com/NataliaLKB/learn-git-basics/blob/991f95ebf6e715bc787b50ab68b4c6eff7791c2e/README.md#github-flow) in Natalia's workshop that explain this.

Useful resources:
+ [understanding github flow](https://guides.github.com/introduction/flow/)
+ [git flow vs github flow](https://lucamezzalira.com/2014/03/10/git-flow-vs-github-flow/)
+ Dev at GitHub [explaining why github flow > git flow](http://scottchacon.com/2011/08/31/github-flow.html)

**Comment by zurda** [comment]
This might have been fixed because I currently see this is mentioned both in the summary and step 3: 

> Workshop summary
> An exercise to practice git workflow skills. The workshop should be undertaken by two programmers, working on two computers. The skills practiced include:
> cloning a repository
> creating branches
> switching branches

...

> There are many types of workflow. At FAC, we use the GitHub flow, where the master branch is always deployable. In this flow, each branch is used for a separate feature. 

Am I correct in assuming this is resolved @jsms90 and can be closed ?
