### ISSUE TITLE
Fix spelling typo in <h1> heading

### ISSUE THREAD

**Issue by sajedazoabi** [foundersandcoders/git-workflow-workshop-for-two#41]
Spelling mistake in the heading (the word 'WORKSHOW' should be replaced with 'WORKSHOP')

**Comment by jsms90** [comment]
Hey @sajedazoabi

Good spot :wink: but this was actually an intentional part of the workshop. We should probably make people aware of that thougha :sweat_smile:

**Comment by lucymk** [comment]
Closing as not an issue with the workshop :upside_down_face:
