### ISSUE TITLE
Extra resources used in London

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/git-workflow-workshop-for-two#42]
To explain github flow mentors in london used the following resources - it may be useful to incorporate these into the workshop in the future:

- https://guides.github.com/introduction/flow/
- the following image was circulated
<img width="649" alt="screen shot 2017-06-27 at 21 02 52" src="https://user-images.githubusercontent.com/14337958/32102390-fe671d38-bb13-11e7-827c-b8e682c6dd5d.png">

(text version below if this is to be added)

1 | git   clone | Clones git repository
-- | -- | --
2 | git   branch branch-name       (or) git branch -b branch-name | Creates a branch for you to work on        Creates and checks out branch
3 | git   checkout branch-name | Moves to new branch
** | Do some work | **
4 | git add   filename   git add   . | Adds changes to staging area
5 | git   commit -m 'info about commit     related to #1' | Commits changes with a messages
6 | git   checkout master | Moves to master
7 | git   pull origin master | Check to see if the master has changed
8 | git   checkout branch-name | Moves back to branch
9 | git   merge master       At this point you may have   conflict issues. You will need to resolve these in the text editor to   continue. The following steps assume there was a conflict. If not skip to   step 12 | Merges from the master into your current branch
10 | git add   filename    git add   . |  
11 | git   commit -m 'info about commit     related to #1' |  
12 | git   push origin branch-name | Pushes branch to remote GitHub

**Comment by lucymk** [comment]
Can this be closed @astroash
