### ISSUE TITLE
Section 2 step 1

### ISSUE THREAD

**Issue by sbinlondon** [foundersandcoders/git-workflow-workshop-for-two#52]
_Splitting the work - Step 1 - Programmer 2 clones the repo_

This asks for 'programmer 2' to clone the repo. However, when we went through the workshop, we were told to both do section 1, so we've both already cloned the repo onto our computers. 

Can we clarify - do both programmers both go through section 1 on their individual computers; or does one person do it while the other person raises issues etc. via Github?

If both programmers do section 1 at the same time on their own computers, then this step is not needed as we only need to $ git pull origin master to update after the pull request bit.

**Comment by helenzhou6** [comment]
I think the intended current set up is for Steps 1 to 7 in Section 1 to all be completed by Programmer 1 within the pair. I got confused over the current instructions myself (sorry).

Perhaps to mitigate any confusion there could be a sentence at the beginning of the workshop that states "within your pair, allocate one to be 'Programmer 1' and the second to be 'Programmer 2'." And then for each individual instruction, it could mention which Programmer will be doing it - for example `1. Programmer 1 creates...`

**Comment by zurda** [comment]
To combine both of your comments, @helenzhou6 and @sbinlondon - would adding the next sentence solve this issue: 

> You're working in a team of two on a project for a new client. Steps 1 to 8 in this section should be completed by one of you, which we'll refer to as `Programmer 1`.

Please feel free to suggest a better phrasing.
