### ISSUE TITLE
Suggest improvement to step 13 

### ISSUE THREAD

**Issue by ali-7** [foundersandcoders/git-workflow-workshop-for-two#54]
I have some suggestions to improve step 13, to emulate the flow as if the students actually work on project.
As we know that you should never merge your pull request or your branch by yourself, so step 13 now, makes Programmer 2 tries to make a merge locally, to see the changes and the conflict that will result from this step.
So, my suggestion is to remove this step and make it that if Programmer 2 pushes his work to the repo and see the conflict in remote and try to resolve it then ( makes it easier to student to see this step before they dive in in next project and face this problem )

**Comment by m4v15** [comment]
Hi Ali!

Thanks for the suggestion! 

However, I would disagree that this is a better flow, people should be merging locally  before pushing a branch and finding out from GitHub. 

The reason for merging locally isn't just to check for merge conflicts, but also to check that the code still runs as it should once it is merged with master - even if there are no merge conflicts, master might have been updated in a way that breaks the code on you branch.

Maybe your suggestion is good as demonstration of visualising merge conflicts, but I would not recommend that this is the flow people should be using - if people are using this later on in the course on projects, I would argue it is a wrong flow.

**Comment by ali-7** [comment]
@m4v15  your explanation make since now, i used this flow until yesterday when i re-read the workshop and find out (really, never used it ) about the local merge, i'll try to use this flow.  

- my flow is to always make a pull origin master in my current branch before i push my branch to github, and there i can see the changes to master and the conflicts if there is any, and fix it and then push the branch to remote, my flow make since and your explanation also make since, and i think it also the same flow but different approach, (please correct me if 'm wrong)

**Comment by zurda** [comment]
@ali-7 @eliascodes , Is there an action required here, a discussion, or could we close it?  I'm also for merging locally, but if the discussion is still going - it's worth keeping this open.

**Comment by ali-7** [comment]
I thought I close it :smiley:
